USE `wx_sms`;
SET NAMES utf8;
--insert into meal_list(name, img_path, count, price) values('红烧牛肉饭', '/image/head.jpg', 10, 10.00),('红烧排骨套餐','/image/head.jpg', 10, 12.00),('西红柿蛋饭', '/image/head.jpg',10, 9.00);
insert into meal_list(name, img_path, count, price) values('红烧猪脚', '/image/hszj.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('红烧带鱼', '/image/hsdy.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('咸水鸭', '/image/xsy.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('糖醋肉', '/image/tcr.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('红烧排骨', '/image/hspg.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('辣子鸡', '/image/lzj.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('红烧鱼', '/image/hsy.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('卤鸡腿', '/image/ljt.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('笋干炒肉', '/image/sgcr.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('葱烧鸡边翅', '/image/csjbc.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('炸鸡翅', '/image/zjc.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('剁椒鱼头', '/image/djyt.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('姜母鸭', '/image/jmy.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('宫保鸡丁', '/image/gbjd.jpg', 10, 14.00);
insert into meal_list(name, img_path, count, price) values('卤肉', '/image/lr.jpg', 10, 14.00);
